<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="pt-br">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Aliança</title>
		<link rel="stylesheet" type="text/css" href="styles/layout_C.css" />
	</head>
	<body>
		<div id="corpo">
			<div id="topo">
				<div id="topoDireita">
					<a href="portugues.html"><img src="img/icones/portugues_topo_icon.png"/></a>
					<a href="ingles.html"><img src="img/icones/ingles_topo_icon.png"/></a>
					<a href="espanhol.html"><img src="img/icones/espanhol_topo_icon.png"/></a>
					<a href="ajuda.html"><img src="img/icones/ajuda_topo_icon.png"/></a>
				</div>
			</div>
			<div id="menuWrapper">
				<a href="home_C.html"><img id="logo" src="img/logos/alianca_logo.png"/></a>
				<ul>
					<li><a href="">Entrar</a></li>
					<li><a href="<?=$this->url(array("controller"=>"cadastro","action"=>"index"),null,true)?>">Cadastre-se</a></li>
					<li><a href="">Quem somos</a></li>
					<li><a href="">Contato</a></li>
					<li><a href="">FAQ</a></li>
					<li><a href="">Planos</a></li>
				</ul>
			</div>
			<div id ="home_bloco_1">
				<div id="home_bloco_1_esq">
					<p class="caixa_alta"> Agregando qualidade ao seu projeto!
					</p>
					<p class="caixa_media">Breve descrição do sistema AliançA. Vitis e adipiscing enim.
					Nam varius eleifend orci, sed viverra nisl condimentum ut. Donec eget justo enim.
					Atirei o pau no gatis. Quisque dignissim felis quis sapien ullamcorper varius tempor sem varius.
					Vivamus lobortis posuere facilisis.
					</p>
					<a href="<?=$this->url(array("controller"=>"cadastro","action"=>"index"),null,true)?>" id="link_cadastro">
						<div id="botao_venda"><p id="cadastre-se">Cadastre-se</p></div>
					</a>
				</div>
				<div id="homeBloco1Dir">
					<div id ="slide">
						<img id = "slide_img"src="img/div_slides/slide_1_0.png"/>
					</div>
					<div id="blocoControle">
						<div id="blocoCentral">
							<a href="" class="move">
								<img class="controle" src="img/div_slides/left_0.png"/>
							</a>
							<a href="" class="move">
								<img class="controle" src="img/div_slides/pause_0.png"/>
							</a>
							<a href="" class="move">
								<img class="controle" src="img/div_slides/right_0.png"/>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div id="linhaHorizontal">
			</div>
			<div id ="home_bloco_2">
				<div id="home_bloco_2_esq_sup">
					<div id="home_bloco_esq_sup_2_central">
						<div class="vantagem">
							<a href="">
								<img class="img_vantagem" src="img/icones/tools_0.png"/>
							</a>
							<p class="texto_vantagem">Funcional
							</p>
						</div>
						<div class="vantagem">
							<a href="">
								<img class="img_vantagem" src="img/icones/functions_0.png"/>
							</a>
							<p class="texto_vantagem">Versátil
							</p>
						</div>
						<div class="vantagem">
							<a href="">
								<img class="img_vantagem" src="img/icones/safe_0.png"/>
							</a>
							<p class="texto_vantagem">Seguro
							</p>
						</div>
						<div class="vantagem">
							<a href="">
								<img class="img_vantagem" src="img/icones/clock_0.png"/>
							</a>
							<p class="texto_vantagem">Online 24 horas
							</p>
						</div>
						<div class="vantagem">
							<a href="">
								<img class="img_vantagem" src="img/icones/light_0.png"/>
							</a>
							<p class="texto_vantagem">Inovador
							</p>
						</div>
						<div class="vantagem">
							<a href="">
								<img class="img_vantagem" src="img/icones/money_0.png"/>
							</a>
							<p class="texto_vantagem">Acessível
							</p>
						</div> 
					</div>
				</div>
				<div id="home_bloco_2_dir">
					<p class="scrum"> O que é SCRUM?
					</p>
					<p class="scrum_media">Breve descrição da metodologia SCRUM:</br></br>
					* Nam varius eleifend orci, sed viverra nisl condimentum ut. Donec eget justo enim.</br>
					* Atirei o pau no gatis. Quisque dignissim felis quis sapien ullamcorper varius tempor sem varius.</br>
					* Vivamus lobortis posuere facilisis.</br>
					* Ispecialista in mé intendi tudis numa galada, vinho, uiski, cariri, rum da jamaikis, so num pode ser mijis</br>
					* Nam varius eleifend orci, sed viverra nisl condimentum ut. Donec eget justo enim.</br>
					* Atirei o pau no gatis. Quisque dignissim felis quis sapien ullamcorper varius tempor sem varius.</br>
					* Vivamus lobortis posuere facilisis.</br>
					* Ispecialista in mé intendi tudis numa galada, vinho, uiski, cariri, rum da jamaikis, so num pode ser mijis
					</p>
				</div>
				<div id="home_bloco_2_esq_inf">
					<p id ="titulo_telas">Conheça o AliançA
					</p>
					<div id = "divPromoImgs">
						<a href="">
							<img class="promo_imgs" src="img/telas/sprints.jpg"/>
						</a>
						<a href="">
							<img class="promo_imgs" src="img/telas/equipe.jpg"/>
						</a>
						<a href="">
							<img class="promo_imgs" src="img/telas/backlogs.jpg"/>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div id="rodape">
			<div id="esquerda_rodape">
				<a href="">
					<img class="social_img" src="img/icones_rodape/facebook_0.png" />
				</a>
				<p class="social_texto">Facebook
				</p>
				<a href="">				
					<img class="social_img" src="img/icones_rodape/twitter_0.png" />
				</a>
				<p class="social_texto">Twitter
				</p>
				<a href="">
					<img class="social_img" src="img/icones_rodape/rss-feed_0.png" />
				</a>
				<p class="social_texto">RSS
				</p>
				<a href="">
					<img class="social_img" src="img/icones_rodape/linkedin_0.png" />
				</a>
				<p class="social_texto">Linkedin
				</p>
				<a href="">
					<img class="social_img" src="img/icones_rodape/google-plus_0.png" />
				</a>
				<p class="social_texto">Google+
				</p>
				<a href="">
					<img class="social_img" src="img/icones_rodape/blogger_0.png" />
				</a>
				<p class="social_texto">Blogger
				</p>
			</div>
			<div id="centro_rodape">
				<a href="" class="link_vertical">
					<p class="vertical_texto">Cadastre-se</p>
				</a>
				<a href="" class="link_vertical">
					<p class="vertical_texto">Quem somos</p>
				</a>
				<a href="" class="link_vertical">
					<p class="vertical_texto">Contato</p>
				</a>
				<a href="" class="link_vertical">
					<p class="vertical_texto">FAQ</p>
				</a>
				<a href="" class="link_vertical">
					<p class="vertical_texto">Planos</p>
				</a>
			</div>
			<div id="direita_rodape">
				<a href="melkor.html" class="logo_rodape">
					<img id="logo_melkor" src="img/logos/melkor_logo.png" />
				</a>
				<a href="alianca.html" class="logo_rodape">
					<img id="logo_alianca" src="img/logos/alianca_logo.png" />
				</a>
				<a href="#topo" class="logo_rodape">
					<img id="rodape_topo_img" src="img/icones_rodape/topo_0.png" />
				</a>
				<a href="" id="copyright">
					<p >Todos os direitos reservados - Melkor Solutions</p>
				</a>
			</div>
		</div>
	</body>
</html>

